apiVersion: v1
appVersion: 1.0.0
description: This Chart seemlessly integrates Kubernetes with AWS ECR
keywords:
- aws ecr
- imagePullSecrets
- kubernetes
maintainers:
- email: db2crush@gmail.com
  name: sanggee park
name: aws-ecr-credential
version: 1.0.0
